# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rpr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RockPaperScissors(object):
    def setupUi(self, RockPaperScissors):
        RockPaperScissors.setObjectName("RockPaperScissors")
        RockPaperScissors.resize(1122, 761)
        self.centralwidget = QtWidgets.QWidget(RockPaperScissors)
        self.centralwidget.setObjectName("centralwidget")
        self.frametop = QtWidgets.QFrame(self.centralwidget)
        self.frametop.setGeometry(QtCore.QRect(30, 60, 1061, 441))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.frametop.setFont(font)
        self.frametop.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frametop.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frametop.setObjectName("frametop")
        self.player_move_label = QtWidgets.QLabel(self.frametop)
        self.player_move_label.setGeometry(QtCore.QRect(180, 80, 201, 171))
        self.player_move_label.setText("")
        self.player_move_label.setPixmap(QtGui.QPixmap("/home/blister-pack/Documents/code_projects/1WORK/Projects/rock_paper_scissors/sprites/rock.png"))
        self.player_move_label.setScaledContents(True)
        self.player_move_label.setObjectName("player_move_label")
        self.pc_move_label = QtWidgets.QLabel(self.frametop)
        self.pc_move_label.setGeometry(QtCore.QRect(650, 80, 201, 181))
        self.pc_move_label.setText("")
        self.pc_move_label.setPixmap(QtGui.QPixmap("/home/blister-pack/Documents/code_projects/1WORK/Projects/rock_paper_scissors/sprites/interrogation.png"))
        self.pc_move_label.setScaledContents(True)
        self.pc_move_label.setObjectName("pc_move_label")
        self.comboBox = QtWidgets.QComboBox(self.frametop)
        self.comboBox.setGeometry(QtCore.QRect(200, 320, 151, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.player_score_label = QtWidgets.QLabel(self.frametop)
        self.player_score_label.setGeometry(QtCore.QRect(270, 20, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setStrikeOut(False)
        self.player_score_label.setFont(font)
        self.player_score_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.player_score_label.setTextFormat(QtCore.Qt.PlainText)
        self.player_score_label.setObjectName("player_score_label")
        self.pc_score_label = QtWidgets.QLabel(self.frametop)
        self.pc_score_label.setGeometry(QtCore.QRect(740, 20, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setStrikeOut(False)
        self.pc_score_label.setFont(font)
        self.pc_score_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pc_score_label.setTextFormat(QtCore.Qt.PlainText)
        self.pc_score_label.setObjectName("pc_score_label")
        self.textEdit = QtWidgets.QTextEdit(self.frametop)
        self.textEdit.setGeometry(QtCore.QRect(860, 80, 181, 151))
        self.textEdit.setObjectName("textEdit")
        self.play_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_button.setGeometry(QtCore.QRect(500, 580, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.play_button.setFont(font)
        self.play_button.setObjectName("play_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 10, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        RockPaperScissors.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RockPaperScissors)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1122, 22))
        self.menubar.setObjectName("menubar")
        RockPaperScissors.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RockPaperScissors)
        self.statusbar.setObjectName("statusbar")
        RockPaperScissors.setStatusBar(self.statusbar)

        self.retranslateUi(RockPaperScissors)
        QtCore.QMetaObject.connectSlotsByName(RockPaperScissors)

    def retranslateUi(self, RockPaperScissors):
        _translate = QtCore.QCoreApplication.translate
        RockPaperScissors.setWindowTitle(_translate("RockPaperScissors", "MainWindow"))
        self.comboBox.setItemText(0, _translate("RockPaperScissors", "Rock"))
        self.comboBox.setItemText(1, _translate("RockPaperScissors", "Scissors"))
        self.comboBox.setItemText(2, _translate("RockPaperScissors", "Paper"))
        self.player_score_label.setText(_translate("RockPaperScissors", "0"))
        self.pc_score_label.setText(_translate("RockPaperScissors", "0"))
        self.textEdit.setHtml(_translate("RockPaperScissors", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:26pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Rules:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">-First to score 3 points wins</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">-Computer chooses randomly</span></p></body></html>"))
        self.play_button.setText(_translate("RockPaperScissors", "Play"))
        self.label.setText(_translate("RockPaperScissors", "Rock, Paper, Scissors"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RockPaperScissors = QtWidgets.QMainWindow()
    ui = Ui_RockPaperScissors()
    ui.setupUi(RockPaperScissors)
    RockPaperScissors.show()
    sys.exit(app.exec_())
