# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow:
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(902, 628)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.operatorBox = QtWidgets.QComboBox(self.centralwidget)
        self.operatorBox.setGeometry(QtCore.QRect(400, 120, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(80)
        self.operatorBox.setFont(font)
        self.operatorBox.setObjectName("operatorBox")
        self.operatorBox.addItem("")
        self.operatorBox.addItem("")
        self.operatorBox.addItem("")
        self.operatorBox.addItem("")
        self.input1 = QtWidgets.QTextEdit(self.centralwidget)
        self.input1.setGeometry(QtCore.QRect(120, 120, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.input1.setFont(font)
        self.input1.setObjectName("input1")
        self.input2 = QtWidgets.QTextEdit(self.centralwidget)
        self.input2.setGeometry(QtCore.QRect(630, 120, 131, 91))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.input2.setFont(font)
        self.input2.setObjectName("input2")
        self.calcButton = QtWidgets.QPushButton(self.centralwidget)
        self.calcButton.setGeometry(QtCore.QRect(390, 280, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.calcButton.setFont(font)
        self.calcButton.setObjectName("calcButton")
        self.resultLabel = QtWidgets.QLabel(self.centralwidget)
        self.resultLabel.setGeometry(QtCore.QRect(390, 410, 111, 81))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.resultLabel.setFont(font)
        self.resultLabel.setObjectName("resultLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 902, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Best calculator ever"))
        self.operatorBox.setItemText(0, _translate("MainWindow", "+"))
        self.operatorBox.setItemText(1, _translate("MainWindow", "-"))
        self.operatorBox.setItemText(2, _translate("MainWindow", "/"))
        self.operatorBox.setItemText(3, _translate("MainWindow", "x"))
        self.calcButton.setText(_translate("MainWindow", "Calculate"))
        self.resultLabel.setText(_translate("MainWindow", "RESULT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
